### ISSUE TITLE
Differences with cordova websocket plugin along with mqtt.js?

### ISSUE THREAD

**Issue by KennPunt** [arcoirislabs/cordova-plugin-mqtt#12]
Can you explain what the differences are of using this plugin, next to using the cordova websocket plugin along with mqtt.js?
Advantages? Disadvantages?

**Comment by arcoirislabs** [comment]
@KennPunt 
Let's consider the context of a Cordova application where the app runs in a webview. Now on any platform's webview, there is only single thread to render the webview. 
If you have experienced any Cordova development, the code can stay same in all the platforms but the underlying webview is never consistent throughout the devices, specially in Android. Which means if you are using the JavaScript library of MQTT, which heavily depends on Websocket, will work only if the Websocket is supported by the webview, if it doesn't then the MQTT won't simply work.

**Comment by arcoirislabs** [comment]
You can use Crosswalk but it will make the app heavy. Now let's say we are at this stage able to give a uniform support using Websocket based MQTT library. But the library will create a processing overhead as it will be dealing with the realtime data, which will again take away some of the allocated resources inside the webview and your app may run slow.

So in short 
MQTT JavaScript library 
Advantages:- 
1. Easy to implement.
2. Easy portability between web browser to mobile app.
3. Ideal for mobile sites.

Disadvantages:-
1. No scope for background service implementation uniformly.
2. Works only when the app is foreground. 
3. Very small scope for configuring connection object & pubsub methods.
4. Uses a portion of Webview's limited resources.
 

By using JavaScript libraries for MQTT doesn't allows you to tap into some app specific behaviour handling like background tasking. Hence the app may start working only if the app is in foreground. Hence the JavaScript library is not used during Cordova app development even if it guarantees easiness.

Now coming to plugin implementation. Cordova development aims at uniform codebase theory where it is stated that, whatever heavy tasks we need to perform in the app that may or may not mimic the platform's native features shall be done using the platform's native language.
This gives us an extra ability to perform various tasks in the native domain using resources allocated to native implementation, without overloading the Webview's single thread and we can use that saved resources for something else like better UI rendering or dooms some other specific tasks.
MQTT plugin for Cordova is such an attempt where we are taking the stress of JavaScript implementation to the native side where we can utilise the features allocated to the native libraries which are way more better than the JavaScript. As the native library utilises different resources, which are way more than the Webview's allows the MQTT code to run faster as compared to the JavaScript counterpart.
Also we can do some cool stuff like merging some of the platform's native features to smoothen the working of the library or may be even elaborate certain features. Plus it gives developer to utilise some of the advanced features of native library just using JavaScript.
Cordova plugin like Will topic configuration, better configuration to connection object, changing the quality of service for each payload before publishing and subscribing to individual topics etc.
Advantages:-
1. Fast.
2. Utilising some advanced feature implementations of native libraries by using JavaScript.
3. Underlying native library is more stable than the JavaScript ones.

Disadvantages:-
1. Since the implementation lies on the native side, the developer has to depend upon the author's release cycle, if the developer is not experienced enough to work on the native side

**Comment by arcoirislabs** [comment]
I hope we have answered your question. If you have any more questions feel free to reach. We will try to bring the background implementation as soon as possible

Regards,
Open source team
Arcoiris Labs

**Comment by arcoirislabs** [comment]
Advantages:-
1. Easy to implement.
2. Websocket plugin being supported widely on all the platforms ensure the uniform support on all the platforms.
3. Good for the apps who want to port the mobile web code to a Cordova app.

Disadvantages:-
1. No scope of implementing background operation. This plugin has no capability of operating in background yet but as the implementation is native, we do have plenty of room to implement sticky background service to keep it running in background.
2. Creates an overhead on the Javascript thread due to MQTT.js. Possible reduction in performance.

Cordova MQTT plugin.
Advantages:-
1. Pure native client with JS bindings. 
2. Least overhead on the Javascript code.
3. Event based topic bus to receive the payload.

Disadvantages:-
1. Absence of background implementation but possibility to implement one, which has been planned for next release.

Although the MQTT.js and native library are same on the options and feature level but at the language level, Java library beats the Javascript counterpart. Also it is wise to let the native side do the heavy lifting rather than achieving it in Javascript.

**Comment by KennPunt** [comment]
Thanks!
