### ISSUE TITLE
Why doesnt it support mqtt://

### ISSUE THREAD

**Issue by CheyenneForbes** [arcoirislabs/cordova-plugin-mqtt#22]

**Comment by ameykshirsagar** [comment]
@CheyenneForbes : Because this project is just the wrapper to the native library. So unless the native library supports connection by mqtt:// or mqtts:// the JS part won't allow the connection to be established.

**Comment by signalpoint** [comment]
> Because this project is just the wrapper to the native library.

@ameykshirsagar Would you please provide a URL to the library you are referring to? I'm curious to monitor progress for `mqtt://` and `mqtts://` support.

**Comment by ameykshirsagar** [comment]
@CheyenneForbes @signalpoint 
The thing is mqtt:// & mqtts:// are nothing but tcp:// & tls:// protocols underneath. For representation purposes we use the URL starting with mqtt:// & mqtts:// when we are doing a MQTT connection instead of a standard TCP Socket connection (even in fact MQTT is a socket connection). But under the hood mqtt:// & mqtts:// are replaced by tcp:// & tls:// as mqtt:// & mqtts:// are not standard protocols recognised on transport layer as per the standards.

@signalpoint : This is the [library](https://eclipse.org/paho/clients/android/) thats being used in this plugin
